# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AMIR KHELLA

description: >
  
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://akhella.github.io" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage

name: 'Amir Khella'
bio: >
  I am an entrepreneur, product designer, software engineer, author, and startup advisor. Previously, I have designed and helped launch 12 tech startups, 5 of which have been acquired. Currently, I run several profitable products for designers and product managers, while working on my next startup.

author_image: "/assets/images/author.jpg"
feature_image: "/assets/images/headshot.jpg"
twitter_username: amirkhella
github_username:  akhella

# Google Analytics
analytics_id: "UA-573910-6"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate
